# Generated by Django 4.2 on 2023-05-12 03:27

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='imagen',
            field=models.ImageField(blank=True, default='icon/front-page.png', null=True, upload_to=website.models.Menu.img_upload_to),
        ),
    ]
