# Generated by Django 4.2 on 2023-05-16 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_profileuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio del platillo'),
        ),
    ]
