# Generated by Django 4.2 on 2023-05-20 00:50

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_restaurant_state2_alter_restaurant_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='state2',
        ),
        migrations.AlterField(
            model_name='imgdish',
            name='img',
            field=models.ImageField(default='icon/pizza.png', null=True, upload_to=website.models.ImgDish.img_upload_to),
        ),
    ]
